# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Maksim Kukushkin
name: Maksim Kukushkin
position: PhD Candidate & Research Associate
email: kukushkin@informatik.uni-leipzig.de
description: |-

  I'm a PhD Student in the [Neuromorphic Information Processing Group](https://nmi.informatik.uni-leipzig.de/) at Leipzig University. In addition, I work as a Research Associate in the Digital Research Methods in Medicine Group at Martin Luther University. My PhD is supervised by [Jun.-Prof. Thomas Schmid](https://umh.de/forschung/nachwuchsgruppen/nwg-schmid) and [Prof. Martin Bogdan](https://nmi.informatik.uni-leipzig.de/staff/prof-dr-martin-bogdan/). 

  I was also a visiting PhD student in the [MaVi Group](https://uob-mavi.github.io/) and worked with [Prof. Tilo Burghardt](https://tiloburghardt.github.io/) and [Prof. Majid Mirmehdi](https://majidmirmehdi.github.io/).

  My research interests span the broad area of deep learning, computer vision, hyperspectral imaging, multimodal learning, and action recognition.

  Before PhD, I worked @[CHECK24](https://check24.de) and @[Posterlounge](https://posterlounge.de/).

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://max-kuk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: max-kuk
linkedin_username: maksim-kukushkin
orcid: 0009-0006-1014-6339
researchgate_username: Maksim_Kukushkin
google_scholar: C3_VIssAAAAJ
google_analytics: G-EH11GZ27SW

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
